schema_version: 1

context:
  version: 1.9.1

package:
  name: nbqa
  version: ${{ version }}

source:
- url: https://files.pythonhosted.org/packages/source/n/nbqa/nbqa-${{ version }}.tar.gz
  sha256: a1f4bcf587c597302fed295951001fc4e1be4ce0e77e1ab1b25ac2fbe3db0cdd

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - nbqa = nbqa.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools <81.0.0
  run:
    - python >=${{ python_min }},<4
    - autopep8 >=1.5
    - ipython >=7.8.0
    - tokenize-rt >=3.2.0
    - tomli

tests:
  - python:
      imports:
        - nbqa
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'
    script:
      - nbqa --help

about:
  summary: Run any Python code quality tool on a Jupyter Notebook!
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/nbQA-dev/nbQA
  repository: https://github.com/nbQA-dev/nbQA

extra:
  recipe-maintainers:
    - s-weigand
    - MarcoGorelli
    - girip11
    - rxm7706
